#!/usr/bin/env python3
import os
import subprocess
import re

cinsts = [
    "l_relaxed",
    "l_acquire",
    "l_seq_cst",
    "s_relaxed",
    "s_release",
    "s_seq_cst",
]
cstatements = {
    "l_relaxed": "VAR = atomic_load_explicit(ARG, memory_order_relaxed)",
    "l_acquire": "VAR = atomic_load_explicit(ARG, memory_order_acquire)",
    "l_seq_cst": "VAR = atomic_load_explicit(ARG, memory_order_seq_cst)",
    "s_relaxed": "atomic_store_explicit(ARG, 2,   memory_order_relaxed)",
    "s_release": "atomic_store_explicit(ARG, 2,   memory_order_release)",
    "s_seq_cst": "atomic_store_explicit(ARG, 2,   memory_order_seq_cst)",
}

rvinsts = [
    "l_relaxed.comon",
    "l_acquire.fence",
    "l_acquire.zlasr",
    "l_acquire.aztso",
    "l_seq_cst.fence",
    "l_seq_cst.zlasr",
    "l_seq_cst.aztso",
    "s_relaxed.comon",
    "s_release.fence",
    "s_release.zlasr",
    "s_release.aztso",
    "s_seq_cst.fence",
#    "s_seq_cst.orign",
    "s_seq_cst.zlasr",
    "s_seq_cst.aztso",
]

rvstatements = {
    "l_relaxed.comon": "lw      VAR, (ARG) | ;",
    "l_acquire.fence": "lw      VAR, (ARG) | ;\nfence r ,rw        | ;",
    "l_acquire.zlasr": "lw.aq   VAR, (ARG) | ;",
    "l_acquire.aztso": "lw      VAR, (ARG) | ;",
    "l_seq_cst.fence": "fence rw,rw        | ;\nlw      VAR, (ARG) | ;\nfence r ,rw        | ;",
    "l_seq_cst.zlasr": "lw.aq   VAR, (ARG) | ;",
    "l_seq_cst.aztso": "fence rw,rw        | ;\nlw      VAR, (ARG) | ;",
    "s_relaxed.comon": "sw      VAR, (ARG) | ;",
    "s_release.fence": "fence rw, w        | ;\nsw      VAR, (ARG) | ;",
    "s_release.zlasr": "sw.rl   VAR, (ARG) | ;",
    "s_release.aztso": "sw      VAR, (ARG) | ;",
    "s_seq_cst.fence": "fence rw, w        | ;\nsw      VAR, (ARG) | ;\nfence rw,rw        | ;",
    "s_seq_cst.orign": "fence rw, w        | ;\nsw      VAR, (ARG) | ;",
    "s_seq_cst.zlasr": "sw.rl   VAR, (ARG) | ;",
    "s_seq_cst.aztso": "sw      VAR, (ARG) | ;\nfence rw,rw        | ;",
}

# true iff reordering allowed
cresults = {}  # generated by stage2
rvresults = {} # generated by stage4


def makectest(insta, instb):
    name = f"{insta}-{instb}"
    filename = f"c-{name}.litmus"
    statement_a = cstatements[insta].replace("VAR", "a").replace("ARG", "x")
    statement_b = cstatements[instb].replace("VAR", "b").replace("ARG", "y")
    cprogram = f"""C {name}
{{ [x] = 0; [y] = 0;}}

P0 (atomic_int* x, atomic_int* y) {{
  int a = 3;
  int b = 3;
  {statement_a};
  {statement_b};
}}

P1 (atomic_int* x, atomic_int* y) {{
  atomic_store_explicit(y, 1, memory_order_seq_cst);
  atomic_thread_fence(memory_order_seq_cst);
  atomic_store_explicit(x, 1, memory_order_relaxed);
}}

exists (0:a=0 /\\ 0:b=0 /\\ [x]=0 /\\ [y]=0)
"""
    with open(f"producttests/{filename}", "w") as f:
        f.write(cprogram)
    #print(cprogram)
    pass

def makervtest(insta, instb):
    name = f"{insta}-{instb}"
    filename = f"rv-{name}.litmus"
    statement_a = rvstatements[insta].replace("VAR", "x3").replace("ARG", "x1")
    statement_b = rvstatements[instb].replace("VAR", "x4").replace("ARG", "x2")
    rvprogram = f"""RISCV {name}
{{
0:x1=x; 0:x2=y; 0:x3=3; 0:x4=3;
1:x1=x; 1:x2=y; 1:x3=2; 1:x4=2;
x=0; y=0;
}}
P0                 | P1              ;
{statement_a}
{statement_b}
                   | sw    x4, 0(x2) ;
                   | fence rw, rw    ;
                   | sw    x3, 0(x1) ;
exists (0:x3=0 /\\ 0:x4=0 /\\ x=0 /\\ y=0)
"""
    with open(f"producttests/{filename}", "w") as f:
        f.write(rvprogram)
    #print(rvprogram)
    pass

def runlitmusc(filename):
    cmd = f"_build/install/default/bin/herd7 -set-libdir herd/libdir -show cond -cat herd/libdir/c11_partialSC.cat producttests/{filename}".split(" ")
    result = subprocess.check_output(cmd)
    states = int(re.search(r"States (\d+)", str(result)).group(1))
    return states

def runlitmusrv(filename):
    cmd = f"_build/install/default/bin/herd7 -set-libdir herd/libdir -show cond -cat herd/libdir/riscv.cat producttests/{filename}".split(" ")
    result = subprocess.check_output(cmd)
    states = int(re.search(r"States (\d+)", str(result)).group(1))
    return states

def runlitmusrvt(filename):
    cmd = f"_build/install/default/bin/herd7 -set-libdir herd/libdir -show cond -cat herd/libdir/riscv-tso.cat producttests/{filename}".split(" ")
    result = subprocess.check_output(cmd)
    states = int(re.search(r"States (\d+)", str(result)).group(1))
    return states

def stage1():
    for s1 in cinsts:
        for s2 in cinsts:
            makectest(s1, s2)
    pass

def stage2():
    for s1 in cinsts:
        cresults[s1] = {}
        for s2 in cinsts:
            state = runlitmusc(f"c-{s1}-{s2}.litmus")
            cresults[s1][s2] = (state == 4)
            print(f"{s1} {s2} {cresults[s1][s2]}")
    pass

def stage3():
    for s1 in rvinsts:
        for s2 in rvinsts:
            makervtest(s1, s2)
    pass

def stage4():
    for s1 in rvinsts:
        rvresults[s1] = {}
        for s2 in rvinsts:
            state = runlitmusrv(f"rv-{s1}-{s2}.litmus")
            rvresults[s1][s2] = (state == 4)
            print(f"{s1} {s2} {rvresults[s1][s2]}")
    pass

def stage4t():
    for s1 in rvinsts:
        rvresults[s1] = {}
        for s2 in rvinsts:
            state = runlitmusrvt(f"rv-{s1}-{s2}.litmus")
            rvresults[s1][s2] = (state == 4)
            print(f"{s1} {s2} {rvresults[s1][s2]}")
    pass

def stage5():
    for s1 in rvinsts:
        for s2 in rvinsts:
            cs1 = s1[:9]
            cs2 = s2[:9]
            rvreorder = rvresults[s1][s2]
            creorder  = cresults[cs1][cs2]
            if rvreorder and not creorder:
                print(f"Error: {s1} {s2}")


stage1()
stage2()
stage3()
#stage4()
stage4t()
stage5()
